services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: userdb
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pPassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    image: abhishek7840/user-service:latest
    container_name: user-service
    depends_on:
      - mysql

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker.hub.internal:3306/userdb  # Keep using the internal Docker network address
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password
    networks:
      - app-network

  api-service:
    image: abhishek7840/api-service:latest
    container_name: api-service
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    image: abhishek7840/frontend:latest
    container_name: frontend
    ports:
      - "5500:80"
    networks:
      - app-network

networks:
  app-network:
